### ISSUE TITLE
Fire intersected manually

### ISSUE THREAD

**Issue by Surt** [RadKod/v-lazy-component#17]
Hi, first of all, GREAT COMPONENT, I just falled in love.

It's working great, llike a charm.. but...
I'm wondering if there is any way to "force" ```isIntercepted``` from the component instantiating the ```lazy-component```

I'm triying some children-component inside the intercepted slot to be aware in certain cases. Already done, but since the children-components are not rendered they never fire. It would be great if I can make the lazy-component aware of my wish to force it to ```isIntercepted```.

pseudocode
```
<mycomponent>
     <lazy-component>
           <children-component/>
     <lazy-component/>

    .....my component code needs the lazy one to be `intersected=true` ( so it is rendered and the children component takes action
</mycomponent>
```

P.D. I'm really noob with Vue, maybe there is a way. If not I can send a pull request adding a ```prop``` that syncs with the ```isIntercepted``` data.

**Comment by selimdoyranli** [comment]
hey, sory for late. thank you so much for advice. please check v2.1.0 (new props & usage) and last example in [demo](https://v-lazy-component.vercel.app/). please ping to re-open if it didn't fix issue.
