### ISSUE TITLE
What is wrapper tag?

### ISSUE THREAD

**Issue by lucasDechenier** [RadKod/v-lazy-component#34]
I didn't undestand what is wrapper tag, can anyone explain? or give a example? Thanks for pattient

**Comment by selimdoyranli** [comment]
If you want change html tag of lazy-component you can use this prop. Default uses div tag

Default:

input: `<lazy-component ...>`
output (render): `<div class="v-lazy-component v-lazy-component--loading" ...>`

Customized:

input: `<lazy-component wrapper-tag="table" ...>`
output (render): `<table class="v-lazy-component v-lazy-component--loading" ...>`
